Remove fsmonitor check for remote (network) file systems.
git-for-windows/git pull request #3967
Opened 2022-08-01 22:39 UTC by edecosta-mw

Most modern Samba-based filers have the necessary support to enable fsmonitor on network-mounted repos. Leave the check in place for reporting/logging purposes but do not have it raise an error.

2022-08-02 14:02 UTC, dscho requested changes
Thank you for your contribution!

While I understand your desire (even if I have to ask to explain it better in the commit message, see https://github.blog/2022-06-30-write-better-commits-build-better-projects/ for excellent guidance), allowing the FSMonitor on all remote drives will essentially revert 1e7be10de0d493f471bf102a7eed32da8247c825 and d989b266c1a7ef47f27cec75e90f3dfefbfa0200. Reverting those changes would introduce a regression, and we obviously cannot have that.

How about implementing [that `fsmonitor.allowRemote` option](https://lore.kernel.org/git/16832f8a-c582-23bb-dda9-b7b2597a42eb@jeffhostetler.com/) suggested by @jeffhostetler? That way, we not only would avoid introducing a regression but this massive commit would also be drastically simplified by avoiding any changes to `po/`, too.

2022-08-02 14:22 UTC, edecosta-mw commented
Thanks for the feedback. I wanted to push on the notion that the check was not really necessary in the first place (and thus wouldn't be a regression). However, if the collective wisdom is to implement the fsmonitor.allowRemote option, I'm good with that too.

2022-08-02 14:24 UTC, jeffhostetler commented
Hello and welcome.  I see this is your first contribution to GFW.  And thanks for your interest in FSMonitor.

There are a few issues with your patch that I'd like to go thru here.

1. You should send the change to the upstream mailing list rather than here.  We already have a conversation on it there.
2. Your change affects not only Samba, but file systems mounted via other technologies, such as NFS.
3. Removing the code in the MacOS-specific files is wrong here -- perhaps it might be valid in a later series when/if we validate NFS on MacOS, for example.
4. You can enable Samba usage on Windows by only removing the code in fsm-settings-win32.c (as you did), but the rest of the code should remain (until we also address the MacOS cases).
5. After the call to GetDriveTypeW() we should then confirm that the drive is mounted via SMB and not NFS (unless/until we test those cases too).
6. And there's a test matrix to consider.  {client: windows} x {server: windows, unix, ...} x {fs: SMB, NFS3x, NFS4x, ...}.  It is not sufficient to just test (windows, windows, smb) before enabling this by default.

As I said earlier on the mailing list, I'd really like to have a `fsmonitor.allowRemote` config setting (defaulted for now to false) and let people turn it on when they/we are comfortable with it.

Jeff

2022-08-08 12:24 UTC, dscho commented
@edecosta-mw do you think you can make the indicated changes?

2022-08-08 13:19 UTC, edecosta-mw commented
@dscho - I can absolutely make the changes; I am working on them now. @jeffhostetler indicated that he would prefer to continue this conversation on the main mailing list. My basic plan is:

1. Close this PR and move this conversation back to the email thread that started this discussion
2. Implement `fsmonitor.allowRemote` (and possibly equivalent  switch for fsmonitor--daemon CLI)
3. Complete research into limiting monitoring of remote repos to those mounted via SMB 
4. Based on #3, implement the necessary check and calls into the Windows APIs

I the above sounds good, I'll will move forward.

2022-08-08 13:55 UTC, dscho commented
Sounds good to me!

2022-08-08 19:15 UTC, closed without merging