Synchronize Win32 API bug fixes from main tree
git-for-windows/git pull request #4208
Opened 2023-01-05 16:14 UTC by AtariDreams

These oversights are severe, from using the wrong function to kill threads, to not closing handles of joined threads.

These changes are already in the main git tree, but since rebasing can be a difficult process, I figure why not add these changes now.

2023-01-07 03:20 UTC, rimrul requested changes
Definitely not like this. This is multiple different upstream commits from different upstream branches (including `seen`) squashed into one with a significantly different commit message and a different sign-off.

2023-01-07 03:37 UTC, rimrul commented
> These oversights are severe, from using the wrong function to kill threads, to not closing handles of joined threads.

To Quote J6ts review of the `_endthreadex` commit on the mailing list:

> The commit message is highly exaggerated, though. The bug is by no means
serious. After all, we've been living with it for a decade. Notice that
pthread_exit() is only called when a thread runs into die(). Even though
we have a small memory leak, it does not occur in a loop because, after
one thread dies, we do not tend to keep starting many, many more that
all die.

All in all the issues that are fixed by this aren't as severe as you make them sound.

2023-01-08 14:24 UTC, AtariDreams commented
I will just wait for the main repo to merge then, and hopefully you can then import the changes from there

2023-01-08 14:24 UTC, closed without merging

2023-01-08 21:56 UTC, PhilipOakley commented
@AtariDreams Just a background note that the auto merging of the upstream is described in the build-extra repo in the evergreen.sh and shears.sh scripts. 

The text at [shears.sh#L12-L18](https://github.com/git-for-windows/build-extra/blob/81eaf1b02ac175fedb431068424d0ffc0b5b781a/shears.sh#L12-L18) is a useful description of the 'reverse merge' (invent your own terms here;-) whereby we pretend to completely drop all the Git-for-Windows patches in favour of the upstream Git ([the 'fake' merge](https://github.com/git-for-windows/build-extra/blob/4bd7660129eec2a76047ca6124b9ed5d9685d243/ever-green.sh#L12-L14)), and then rebase all our Git-for-Windows patches on top (and patches which have already been upstreamed are nicely dropped by the rebase). 

Thus, older GfW releases will be found in our main history as the second parent of the reverse (fake) merge, and be **part** of our history, rather than a side branch.

Hopefully that is a useful aside, and I described it without misrepresentation ;-)