[#4766] Win32: Added support NUMA configuration with multiple count CPU sockets
git-for-windows/git pull request #4896
Opened 2024-04-05 09:51 UTC by GermanAizek

Fixed this issue: https://github.com/git-for-windows/git/issues/4766

2024-04-09 20:17 UTC, dscho requested changes
Thank you for contributing this PR! While NUMA is probably still rather uncommon, it'll be good to have the support (once the code compiles, that is).

2024-04-09 20:17 UTC, dscho commented on thread-utils.c
> +	PDWORD);
Please move this code to `compat/win32/` and use `lazyload.h` (imitate existing code that [declares](https://github.com/git-for-windows/git/blob/ad0bbfffa543db6979717be96df630d3e5741331/compat/mingw.c#L2807-L2808) and [initializes](https://github.com/git-for-windows/git/blob/ad0bbfffa543db6979717be96df630d3e5741331/compat/mingw.c#L2812) the function pointer).

2024-04-09 20:17 UTC, dscho commented on thread-utils.c
> +/// defines the GetLogicalProcessorInformationEx function
Please avoid C++-style comments. The existing code does not use them.

2024-04-09 20:17 UTC, dscho commented on thread-utils.c
> +static size_t get_windows_compatible_n_cores() {
Let's not add an extra function here. Instead, let's declare a single `win32_online_cpus(void)` function in a header file in `compat/win32/` and implement it in a `.c` file. Or put them into `compat/mingw.h`/`compat/mingw.c`.

2024-04-09 20:17 UTC, dscho commented on thread-utils.c
> +	GetLogicalProcessorInformationEx(RelationAll, NULL, &length);
Let's not forget to check the return value.

2024-09-04 18:09 UTC, GermanAizek commented
@dscho, I will not be able to fix this branch without testing, I have completely switched to Linux and FreeBSD. Is there anyone who can test this branch with NUMA nodes on any motherboard with two or more processors?

2024-09-04 18:11 UTC, GermanAizek commented
@dscho When I did the fix in this PR, it accurately detected count threads correctly.

2024-09-04 18:16 UTC, GermanAizek commented
@dscho which is very good on Linux there are no such problems and it has been originally laid down by POSIX library, Microsoft provides many methods in Winapi to get count threads, obviously software developers use the most common in tutorials and on stackoverflow, although this is wrong. Because of this on any Windows, only 50% CPU util is used with two NUMA nodes, 25% with 4 nodes, with 6 numa nodes 16.66%

2024-09-05 07:59 UTC, dscho commented
> I will not be able to fix this branch without testing, I have completely switched to Linux and FreeBSD. Is there anyone who can test this branch with NUMA nodes on any motherboard with two or more processors?

That's unfortunate, I have no such system to test, either.

Let's just close this PR until the time when (if?) someone with such a system can test and work on it.

2024-09-05 07:59 UTC, closed without merging